// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectWork.Data;

namespace ProjectWork.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("ProjectWork.Models.Colore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Colori");
                });

            modelBuilder.Entity("ProjectWork.Models.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<double>("Prezzo")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("ProjectWork.Models.Quantita", b =>
                {
                    b.Property<int>("ProdottoId")
                        .HasColumnType("int");

                    b.Property<int>("TagliaId")
                        .HasColumnType("int");

                    b.Property<int>("ColoreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantitativo")
                        .HasColumnType("int");

                    b.HasKey("ProdottoId", "TagliaId", "ColoreId");

                    b.HasIndex("ColoreId");

                    b.HasIndex("TagliaId");

                    b.ToTable("Quantitas");
                });

            modelBuilder.Entity("ProjectWork.Models.Taglia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Taglie");
                });

            modelBuilder.Entity("ProjectWork.Models.Quantita", b =>
                {
                    b.HasOne("ProjectWork.Models.Colore", "Colori")
                        .WithMany()
                        .HasForeignKey("ColoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWork.Models.Prodotto", "Prodotti")
                        .WithMany()
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWork.Models.Taglia", "Taglie")
                        .WithMany()
                        .HasForeignKey("TagliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colori");

                    b.Navigation("Prodotti");

                    b.Navigation("Taglie");
                });
#pragma warning restore 612, 618
        }
    }
}
